FROM node:22

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# COPY . .
# Because bind mount replaces everything anyway => COPY becomes pointless.

EXPOSE ${PORT}

CMD [ "npm", "run", "start:dev" ]